---
# tasks file for poweron
- name: Turn system power on
  community.general.redfish_command:
    category: Systems
    command: PowerOn
    baseuri: "{{ _baseuri_ }}"
    username: "{{ _username_ }}"
    password: "{{ _password_ }}"
