---
# tasks file for cleariellogs
- name: Clear Logs
  community.general.redfish_command:
    category: Manager
    command: ClearLogs
    baseuri: "{{ _baseuri_ }}"
    username: "{{ _username_ }}"
    password: "{{ _password_ }}"
