---
# tasks file for setNTPservers
- name: Set {{ attribute_name }} to {{ attribute_value }}
  community.general.ilo_redfish_config:
    category: Manager
    command: SetNTPServers
    baseuri: "{{ _baseuri_ }}"
    username: "{{ _username_ }}"
    password: "{{ _password_ }}"
    attribute_name: "{{ _attribute_name_ }}"
    attribute_value: "{{ _attribute_value_ }}"
