---
# tasks file for systeminven
- name: Getting system inventory
  community.general.redfish_info:
    category: Systems
    command: GetSystemInventory
    baseuri: "{{ _baseuri_ }}"
    username: "{{ _username_ }}"
    password: "{{ _password_ }}"
  register: result_attr
