---
# tasks file for adduser
- name: Add user
  community.general.redfish_command:
    category: Accounts
    command: AddUser
    baseuri: "{{ _baseuri_ }}"
    username: "{{ _username_ }}"
    password: "{{ _password_ }}"
    new_username: "{{ _new_username_ }}"
    new_password: "{{ _new_password_ }}"
    roleid: "{{ _roleid_ }}"
