---
- hosts: myhosts
  connection: local
  name: Set iLO NIC settings
  gather_facts: false
  # vars_files: iLO_redfish.yml

  vars:
    - dns_server: 192.168.1.1
    - domain_name: tst.sgp.hp.mfg
    - ntp_atrrname: StaticNTPServers
    - ntp_attrvalue: 1.2.3.4
    - WINS_attrname: WINSRegistration
    - attribute_name: HostName
    - attribute_value: ILOSGH924TZ38

  tasks:
    - name: Create session
      community.general.redfish_command:
        category: Sessions
        command: CreateSession
        baseuri: "{{ _baseuri_ }}"
        username: "{{ _username_ }}"
        password: "{{ _password_ }}"
      register: result

    - name: Set {{ ntp_atrrname }} to {{ ntp_attrvalue }}
      community.general.ilo_redfish_config:
        category: Manager
        command: SetNTPServers
        baseuri: "{{ _baseuri_ }}"
        # username: "{{ username }}"
        # password: "{{ password }}"
        attribute_name: "{{ _attribute_name_ }}"
        attribute_value: "{{ _attribute_value_ }}"
        auth_token: "{{ result.session.token }}"

    - name: Set DNS Server to {{ dns_server }}
      community.general.ilo_redfish_config:
        category: Manager
        command: SetDNSserver
        baseuri: "{{ _baseuri_ }}"
        # username: "{{ username }}"
        # password: "{{ password }}"
        attribute_name: DNSServers
        attribute_value: "{{ _attribute_value_ }}"
        auth_token: "{{ result.session.token }}"

    - name: Set Domain name to {{ domain_name }}
      community.general.ilo_redfish_config:
        category: Manager
        command: SetDomainName
        baseuri: "{{ _baseuri_ }}"
        # username: "{{ username }}"
        # password: "{{ password }}"
        attribute_name: DomainName
        attribute_value: "{{ _attribute_value_ }}"
        auth_token: "{{ result.session.token }}"

    - name: Disable {{ WINS_attrname }}
      community.general.ilo_redfish_config:
        category: Manager
        command: SetWINSReg
        baseuri: "{{ _baseuri_ }}"
        # username: "{{ username }}"
        # password: "{{ password }}"
        attribute_name: "{{ _attribute_name_ }}"
        auth_token: "{{ result.session.token }}"

    - name: Set HostName
      community.general.redfish_config:
        category: Manager
        command: SetManagerNic
        nic_config:
          HostName: "{{ attribute_value }}"
        baseuri: "{{ _baseuri_ }}"
        # username: "{{ username }}"
        # password: "{{ password }}"
        auth_token: "{{ result.session.token }}"

    - name: Delete session using security token created by CreateSesssion above
      community.general.redfish_command:
        category: Sessions
        command: DeleteSession
        baseuri: "{{ _baseuri_ }}"
        auth_token: "{{ result.session.token }}"
        session_uri: "{{ result.session.uri }}"
