---
- hosts: myhosts
  connection: local
  name: Set TimeZone
  gather_facts: false
  # vars_files: iLO_redfish.yml

  vars:
    - attribute_value: Chennai

  tasks:
    - name: Create session
      community.general.redfish_command:
        category: "Sessions"
        command: "CreateSession"
        baseuri: "{{ _baseuri_ }}"
        username: "{{ _username_ }}"
        password: "{{ _password_ }}"
      register: result

    - name: Set TimeZone to {{ attribute_value }}
      community.general.ilo_redfish_config:
        category: "Manager"
        command: "SetTimeZone"
        baseuri: "{{ _baseuri_ }}"
            # username: "{{ username }}"
            # password: "{{ password }}"
        attribute_name: "TimeZone"
        attribute_value: "{{ _attribute_value_ }}"
        auth_token: "{{ result.session.token }}"

    - name: Delete session using security token created by CreateSesssion above
      community.general.redfish_command:
        category: "Sessions"
        command: "DeleteSession"
        baseuri: "{{ _baseuri_ }}"
        auth_token: "{{ result.session.token }}"
        session_uri: "{{ result.session.uri }}"

