---
- hosts: myhosts
  connection: local
  name: Set boot mode to Legacy BIOS and reboot
  gather_facts: false
  # vars_files: iLO_redfish.yml

  vars:
    - bios_attr: { BootMode: LegacyBios } # The dictionary is of the format {"attribute_name" : "attribute_value"}

  tasks:
    - name: Create session
      community.general.redfish_command:
        category: Sessions
        command: CreateSession
        baseuri: "{{ _baseuri_ }}"
        username: "{{ _username_ }}"
        password: "{{ _password_ }}"
      register: result

    - name: Set {{ bios_attr }}
      community.general.redfish_config:
        category: Systems
        command: SetBiosAttributes
        bios_attributes: "{{ _bios_attributes_ }}"
        baseuri: "{{ _baseuri_ }}"
        # username: "{{ username }}"
        # password: "{{ password }}"
        auth_token: "{{ result.session.token }}"
      register: bios_attribute

    - name: Reboot system to apply new BIOS settings
      community.general.redfish_command:
        category: Systems
        command: PowerReboot
        baseuri: "{{ _baseuri_ }}"
        # username: "{{ username }}"
        # password: "{{ password }}"
        auth_token: "{{ result.session.token }}"
      when: bios_attribute.changed

    - name: Delete session using security token created by CreateSesssion above
      community.general.redfish_command:
        category: Sessions
        command: DeleteSession
        baseuri: "{{ _baseuri_ }}"
        auth_token: "{{ result.session.token }}"
        session_uri: "{{ result.session.uri }}"
