---
- hosts: myhosts
  connection: local
  name: Set one-time BIOS boot device
  gather_facts: false
  # vars_files: iLO_redfish.yml

  # ONLY WORKS IN LEGACY BIOS MODE!
  #
  # Bootdevice options include: None, Pxe, Cd, Floppy, Hdd, BiosSetup,
  # Utilities, UefiTarget & SDCard.

  vars:
    - bootdevice: Pxe

  tasks:
    - name: Create session
      community.general.redfish_command:
        category: Sessions
        command: CreateSession
        baseuri: "{{ _baseuri_ }}"
        username: "{{ _username_ }}"
        password: "{{ _password_ }}"
      register: result

    - name: Set one-time boot device to {{ bootdevice }}
      community.general.redfish_command:
        category: Systems
        command: SetOneTimeBoot
        bootdevice: "{{ _bootdevice_ }}"
        baseuri: "{{ _baseuri_ }}"
        # username: "{{ username }}"
        # password: "{{ password }}"
        auth_token: "{{ result.session.token }}"
      register: bios_onetimeboot

    - name: Delete session using security token created by CreateSesssion above
      community.general.redfish_command:
        category: Sessions
        command: DeleteSession
        baseuri: "{{ _baseuri_ }}"
        auth_token: "{{ result.session.token }}"
        session_uri: "{{ result.session.uri }}"
