---
# tasks file for get_software_inventory
- name: Get Software Inventory
  community.general.redfish_info:
    category: Update
    command: GetSoftwareInventory
    baseuri: "{{ _baseuri_ }}"
    # username: "{{ username }}"
    # password: "{{ password }}"
    auth_token: "{{ _auth_token_ }}"
  register: result_attr
