---
# tasks file for get_network_protocols
- name: Get Network Protocols
  community.general.redfish_info:
    category: Manager
    command: GetNetworkProtocols
    baseuri: "{{ _baseuri_ }}"
    # username: "{{ username }}"
    # password: "{{ password }}"
    auth_token: "{{ _auth_token_ }}"
  register: result_attr
