---
# tasks file for get_host_interfaces
- name: Get Host Interfaces
  community.general.redfish_info:
    category: Manager
    command: GetHostInterfaces
    baseuri: "{{ _baseuri_ }}"
    # username: "{{ username }}"
    # password: "{{ password }}"
    auth_token: "{{ _auth_token_ }}"
  register: result_attr
