---
# tasks file for systemreboot
- name: Reboot system
  community.general.redfish_command:
    category: Systems
    command: PowerReboot
    baseuri: "{{ _baseuri_ }}"
    username: "{{ _username_ }}"
    password: "{{ _password_ }}"
