---
# tasks file for setTimeZone
- name: Set TimeZone to {{ attribute_value }}
  community.general.ilo_redfish_config:
    category: Manager
    command: SetTimeZone
    baseuri: "{{ _baseuri_ }}"
    username: "{{ _username_ }}"
    password: "{{ _password_ }}"
    attribute_name: TimeZone
    attribute_value: "{{ _attribute_value_ }}"
