---
# tasks file for setDomainName
- name: Set Domain name to {{ domain_name }}
  community.general.ilo_redfish_config:
    category: Manager
    command: SetDomainName
    baseuri: "{{ _baseuri_ }}"
    username: "{{ _username_ }}"
    password: "{{ _password_ }}"
    attribute_name: DomainName
    attribute_value: "{{ _attribute_value_ }}"
